version: "3.9"  # optional since v1.27.0
services:
  podman:
    pull_policy: always
    image: ghcr.io/project0/podman-container:${PODMAN_VERSION:-latest}
    ports:
      - "10888:10888"
    cap_add:
      - sys_admin
      - mknod
    devices:
      - /dev/fuse
    privileged: true
